import Preloader from "@/layout/Preloader";
import "@css/icon.css";
import "@css/plugin.css";
import "@css/spacing.css";
import "@css/style.css";
import "@css/responsive.css";
import "./globals.css";

export const metadata = {
  title: "Petrix - Personal Portfolio React NextJS Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Preloader />
        {children}
      </body>
    </html>
  );
}
